import React from "react";

import Style from "./index.module.less";

const Policy: React.FC = () => {
  const TitleStyle: React.CSSProperties = {
    color: "#6796e6",
  };

  const ContentStyle: React.CSSProperties = {
    color: "#cccccc",
  };

  return (
    <div className={Style.policy}>
      <div className={Style.title}>Dinero Privacy Policy</div>
      <div>
        <p>
          <span style={TitleStyle}>1.</span>
          <span style={ContentStyle}> Introduction</span>
        </p>
        <p>
          <span style={ContentStyle}>
            This Privacy Policy sets out how we, Dinero Messenger Inc.
            (“Dinero”), use and protect your personal data that you provide to
            us, or that is otherwise obtained or generated by us, in connection
            with your use of our cloud-based messaging services (the
            “Services”). For the purposes of this Privacy Policy, ‘we’, ‘us’ and
            ‘our’ refers to Dinero, and ‘you’ refers to you, the user of the
            Services.
          </span>
          <br />
        </p>
        <p>
          <span style={ContentStyle}>1.1 Privacy Principles</span>
        </p>
        <p>
          <span style={ContentStyle}>
            Dinero has two fundamental principles when it comes to collecting
            and processing private data:
          </span>
          <br />
        </p>
        <p>
          <span style={ContentStyle}>
            We don't use your data to show you ads.
          </span>
        </p>
        <p>
          <span style={ContentStyle}>
            We only store the data that Dinero needs to function as a secure and
            feature-rich messaging service.
          </span>
        </p>
        <p>
          <span style={ContentStyle}>1.2. Terms of Service</span>
        </p>
        <p>
          <span style={ContentStyle}>
            This Privacy Policy forms part of our Terms of Service, which
            describes the terms under which you use our Services and which are
            available at https://aimessenger.mystrikingly.com. This Privacy
            Policy should therefore be read in conjunction with those terms.
          </span>
          <br />
        </p>
        <p>
          <span style={ContentStyle}>1.3. Table of Contents</span>
        </p>

        <p>
          <span style={ContentStyle}>
            This Privacy Policy explains the following:
          </span>
          <br />
        </p>
        <p>
          <span style={ContentStyle}>
            the legal basis for processing your personal data;
          </span>
        </p>
        <p>
          <span style={ContentStyle}>
            what personal data we may collect from you;
          </span>
        </p>
        <p>
          <span style={ContentStyle}>how we keep your personal data safe;</span>
        </p>
        <p>
          <span style={ContentStyle}>
            what we may use your personal data for;
          </span>
        </p>
        <p>
          <span style={ContentStyle}>
            who your personal data may be shared with; and
          </span>
        </p>
        <p>
          <span style={ContentStyle}>
            your rights regarding your personal data.
          </span>
        </p>
        <p>
          <span style={ContentStyle}>1.4. EEA Representative</span>
        </p>
        <p>
          <span style={ContentStyle}>
            If you live in a country in the European Economic Area (EEA), the
            Services are provided by Dinero, which for the purposes of
            applicable data protection legislation is the data controller
            responsible for your personal data when you use our Services.
            However, as Dinero is located outside the EEA, we have designated a
            third party, European Data Protection Office (EDPO), as our
            representative pursuant to Article 27 of the GDPR. You can direct to
            EDPO any of your GDPR-related queries:
          </span>
          <br />
        </p>
        <p>
          <span style={ContentStyle}>
            by using EDPO’s online request form at
            https://edpo.com/gdpr-data-request/ or
          </span>
        </p>
        <p>
          <span style={ContentStyle}>
            by writing to EDPO at Avenue Huart Hamoir 71, 1030 Brussels,
            Belgium.
          </span>
        </p>
        <p>
          <span style={TitleStyle}>2.</span>
          <span style={ContentStyle}>
            {" "}
            Legal Ground for Processing Your Personal Data
          </span>
        </p>
        <p>
          <span style={ContentStyle}>
            We process your personal data on the ground that such processing is
            necessary to further our legitimate interests (including: (1)
            providing effective and innovative Services to our users; and (2) to
            detect, prevent or otherwise address fraud or security issues in
            respect of our provision of Services), unless those interests are
            overridden by your interest or fundamental rights and freedoms that
            require protections of personal data.
          </span>
          <br />
        </p>
        <p>
          <span style={TitleStyle}>3.</span>
          <span style={ContentStyle}> What Personal Data We Use</span>
        </p>
        <p>
          <span style={ContentStyle}>3.1. Basic Account Data</span>
        </p>
        <p>
          <span style={ContentStyle}>
            Dinero is a communication service. You provide your mobile number
            and basic account data (which may include profile name, profile
            picture and about information) to create a Dinero account.
          </span>
          <br />
        </p>
        <p>
          <span style={ContentStyle}>
            To make it easier for your contacts and other people to reach you
            and recognize who you are, the screen name you choose, your profile
            pictures, and your username (should you choose to set one) on Dinero
            are always public. We don't want to know your real name, gender, age
            or what you like.
          </span>
          <br />
        </p>
        <p>
          <span style={ContentStyle}>
            We do not require your screen name to be your real name. Note that
            users who have you in their contacts will see you by the name they
            saved and not by your screen name. This way your mother can have the
            public name 'Johnny Depp' while appearing as 'Mom' to you and as
            'Boss' to her underlings at work (or the other way around, depending
            on how these relationships are structured).
          </span>
          <br />
        </p>
        <p>
          <span style={ContentStyle}>3.2. Your Email Address</span>
        </p>
        <p>
          <span style={ContentStyle}>
            When you enable 2-step-verification for your account or store
            documents using the Dinero Passport feature, you can opt to set up a
            password recovery email. This address will only be used to send you
            a password recovery code if you forget it. That's right: no
            marketing or “we miss you” bullshit.
          </span>
          <br />
        </p>
        <p>
          <span style={ContentStyle}>
            From September 2022, we may ask some users to provide an email
            address to receive login codes via email instead of SMS (with an
            option to use 'Sign in With Google' / 'Sign in with Apple'). In this
            case, we will receive an email address which will be stored
            separately from the recovery email, and will only be used to send
            you authentication codes when you log in to your account. The login
            email address will be stored until it is changed or the account is
            deleted.
          </span>
          <br />
        </p>
        <p>
          <span style={ContentStyle}>3.3. Your Messages</span>
        </p>
        <p>
          <span style={ContentStyle}>3.3.1. Cloud Chats</span>
        </p>
        <p>
          <span style={ContentStyle}>
            Dinero is a cloud service. We store messages, photos, videos and
            documents from your cloud chats on our servers so that you can
            access your data from any of your devices anytime without having to
            rely on third-party backups. All data is stored heavily encrypted
            and the encryption keys in each case are stored in several other
            data centers in different jurisdictions. This way local engineers or
            physical intruders cannot get access to user data.
          </span>
          <br />
        </p>
        <p>
          <span style={ContentStyle}>3.3.2. Secret Chats</span>
        </p>
        <p>
          <span style={ContentStyle}>
            Secret chats use end-to-end encryption. This means that all data is
            encrypted with a key that only you and the recipient know. There is
            no way for us or anybody else without direct access to your device
            to learn what content is being sent in those messages. We do not
            store your secret chats on our servers. We also do not keep any logs
            for messages in secret chats, so after a short period of time we no
            longer know who or when you messaged via secret chats. For the same
            reasons secret chats are not available in the cloud — you can only
            access those messages from the device they were sent to or from.
          </span>
          <br />
        </p>
        <p>
          <span style={ContentStyle}>3.3.3. Media in Secret Chats</span>
        </p>
        <p>
          <span style={ContentStyle}>
            When you send photos, videos or files via secret chats, before being
            uploaded, each item is encrypted with a separate key, not known to
            the server. This key and the file’s location are then encrypted
            again, this time with the secret chat’s key — and sent to your
            recipient. They can then download and decipher the file. This means
            that the file is technically on one of Dinero’s servers, but it
            looks like a piece of random indecipherable garbage to everyone
            except for you and the recipient. We don’t know what this random
            data stands for and we have no idea which particular chat it belongs
            to. We periodically purge this random data from our servers to save
            disk space.
          </span>
          <br />
        </p>
        <p>
          <span style={ContentStyle}>3.3.4. Public Chats</span>
        </p>
        <p>
          <span style={ContentStyle}>
            In addition to private messages, Dinero also supports public
            channels and public groups. All public chats are cloud chats (see
            section 3.3.1 above). Like everything on Dinero, the data you post
            in public communities is encrypted, both in storage and in transit —
            but everything you post in public will be accessible to everyone.
          </span>
          <br />
        </p>
        <p>
          <span style={ContentStyle}>3.4. Phone Number and Contacts</span>
        </p>
        <p>
          <span style={ContentStyle}>
            Dinero uses phone numbers as unique identifiers so that it is easy
            for you to switch from SMS and other messaging apps and retain your
            social graph. We ask your permission before syncing your contacts.
          </span>
          <br />
        </p>
        <p>
          <span style={ContentStyle}>
            We store your up-to-date contacts in order to notify you as soon as
            one of your contacts signs up for Dinero and to properly display
            names in notifications. We only need the number and name (first and
            last) for this to work and store no other data about your contacts.
          </span>
          <br />
        </p>
        <p>
          <span style={ContentStyle}>
            Our automatic algorithms can also use anonymized sets of phone
            numbers to calculate the approximate number of potential contacts an
            unregistered phone number may have on Dinero. When you open the
            'Invite friends' interface, we display the resulting statistics next
            to your contacts to give you an idea of who could benefit most from
            joining Dinero.
          </span>
          <br />
        </p>
        <p>
          <span style={ContentStyle}>
            You can always stop syncing contacts or delete them from our servers
            in Settings &gt; Privacy &amp; Security &gt; Data Settings.
          </span>
          <br />
        </p>
        <p>
          <span style={ContentStyle}>
            If you are using Android, Dinero will ask you for permission to
            access your phone call logs (READ_CALL_LOG). If you grant this
            permission, Dinero will be able verify your account by transmitting
            a phone call instead of asking you to enter a code. Dinero uses this
            permission only to confirm receipt of the confirmation call by
            verifying the number in the call log.
          </span>
          <br />
        </p>
        <p>
          <span style={ContentStyle}>3.5. Location Data</span>
        </p>
        <p>
          <span style={ContentStyle}>
            If you share a location in a chat, this location data is treated
            like other messages in cloud or secret chats respectively.
          </span>
          <br />
        </p>
        <p>
          <span style={ContentStyle}>
            If you share your Live Location in any chat or turn on ’Make Myself
            Visible’ in People Nearby, Dinero will use your data to display your
            location to those users with whom you are sharing it, even when the
            app is closed – for as long as you keep these optional features
            activated.
          </span>
          <br />
        </p>
        <p>
          <span style={ContentStyle}>3.6. Cookies</span>
        </p>
        <p>
          <span style={ContentStyle}>
            The only cookies we use are those to operate and provide our
            Services on the web. We do not use cookies for profiling or
            advertising. The cookies we use are small text files that allow us
            to provide and customize our Services, and in doing so provide you
            with an enhanced user experience. Your browser should allow you to
            control these cookies, including whether or not to accept them and
            how to remove them. You may choose to block cookies with your web
            browser, however, if you do disable these cookies you will not be
            able to log in to Dinero Web.
          </span>
          <br />
        </p>
        <p>
          <span style={TitleStyle}>4.</span>
          <span style={ContentStyle}> Keeping Your Personal Data Safe</span>
        </p>
        <p>
          <span style={ContentStyle}>4.1. Storing Data</span>
        </p>
        <p>
          <span style={ContentStyle}>
            If you signed up for Dinero from the UK or the EEA, your data is
            stored in data centers in the Netherlands. These are third-party
            provided data centers in which Dinero rents a designated space.
            However, the servers and networks that sit inside these data centers
            and on which your personal data is stored are owned by Dinero. As
            such, we do not share your personal data with such data centers. All
            data is stored heavily encrypted so that local Dinero engineers or
            physical intruders cannot get access.
          </span>
          <br />
        </p>
        <p>
          <span style={ContentStyle}>4.2. End-to-End Encrypted Data</span>
        </p>
        <p>
          <span style={ContentStyle}>
            Your messages, media and files from secret chats (see section 3.3.2
            above), as well as the contents of your calls and the data you store
            in your Dinero Passport are processed only on your device and on the
            device of your recipient. Before this data reaches our servers, it
            is encrypted with a key known only to you and the recipient. While
            Dinero servers will handle this end-to-end encrypted data to deliver
            it to the recipient – or store it in the case of Dinero Passport
            data, we have no ways of deciphering the actual information. In this
            case, we neither store nor process your personal data, rather we
            store and process random sequences of symbols that have no meaning
            without the keys which we don’t have.
          </span>
          <br />
        </p>
        <p>
          <span style={ContentStyle}>4.3. Retention</span>
        </p>
        <p>
          <span style={ContentStyle}>
            Unless stated otherwise in this Privacy Policy, the personal data
            that you provide us will only be stored for as long as it is
            necessary for us to fulfill our obligations in respect of the
            provision of the Services.
          </span>
          <br />
        </p>
        <p>
          <span style={TitleStyle}>5.</span>
          <span style={ContentStyle}> Processing Your Personal Data</span>
        </p>
        <p>
          <span style={ContentStyle}>5.1. Our Services</span>
        </p>
        <p>
          <span style={ContentStyle}>
            Dinero is a cloud service. We will process your data to deliver your
            cloud chat history, including messages, media and files, to any
            devices of your choosing without a need for you to use third-party
            backups or cloud storage.
          </span>
          <br />
        </p>
        <p>
          <span style={ContentStyle}>5.2. Safety and Security</span>
        </p>
        <p>
          <span style={ContentStyle}>
            Dinero supports massive communities which we have to police against
            abuse and Terms of Service violations. Dinero also has more than 700
            million users which makes it a lucrative target for spammers. To
            improve the security of your account, as well as to prevent spam,
            abuse, and other violations of our Terms of Service, we may collect
            metadata such as your IP address, devices and Dinero apps you've
            used, history of username changes, etc. If collected, this metadata
            can be kept for 12 months maximum.
          </span>
          <br />
        </p>
        <p>
          <span style={ContentStyle}>5.3. Spam and Abuse</span>
        </p>
        <p>
          <span style={ContentStyle}>
            To prevent phishing, spam and other kinds of abuse and violations of
            Dinero’s Terms of Service, our moderators may check messages that
            were reported to them by their recipients. If a spam report on a
            message you sent is confirmed by our moderators, your account may be
            limited from contacting strangers – temporarily or permanently. You
            can send an appeal using @Spambot. In case of more serious
            violations, your account may be banned. We may also use automated
            algorithms to analyze messages in cloud chats to stop spam and
            phishing.
          </span>
          <br />
        </p>
        <p>
          <span style={ContentStyle}>5.4. Cross-Device Functionality</span>
        </p>
        <p>
          <span style={ContentStyle}>
            We may also store some aggregated metadata to create Dinero features
            (see section 5.5 below) that work across all your devices.
          </span>
          <br />
        </p>
        <p>
          <span style={ContentStyle}>5.5. Advanced features</span>
        </p>
        <p>
          <span style={ContentStyle}>
            We may use some aggregated data about how you use Dinero to build
            useful features. For example, when you open the Search menu, Dinero
            displays the people you are more likely to message in a box at the
            top of the screen. To do this, we calculate a rating that shows
            which people you message frequently. A similar rating is calculated
            for inline bots so that the app can suggest the bots you are most
            likely to use in the attachment menu (or when you start a new
            message with “@”). To turn this feature off and delete the relevant
            data, go to Settings &gt; Privacy &amp; Security &gt; Data Settings
            and disable “Suggest Frequent Contacts”.
          </span>
          <br />
        </p>
        <p>
          <span style={ContentStyle}>5.6. No Ads Based on User Data</span>
        </p>
        <p>
          <span style={ContentStyle}>
            Unlike other services, we don't use your data for ad targeting or
            other commercial purposes. Dinero only stores the information it
            needs to function as a secure and feature-rich cloud service.
          </span>
          <br />
        </p>
        <p>
          <span style={ContentStyle}>
            Dinero offers a tool for advertisers to promote their messages in
            public one-to-many channels, but these sponsored messages are based
            solely on the topic of the public channels in which they are shown.
            No user data is mined or analyzed to display ads or sponsored
            messages.
          </span>
          <br />
        </p>
        <p>
          <span style={TitleStyle}>6.</span>
          <span style={ContentStyle}> Bot Messages</span>
        </p>
        <p>
          <span style={ContentStyle}>6.1. Ecosystem</span>
        </p>
        <p>
          <span style={ContentStyle}>
            Dinero has an API that allows third-party developers to create bots.
            Bots are apps that look like special Dinero users: you can talk to
            them from your chat list, add them to groups or use a special
            “inline” interface to access their features. By performing any of
            these actions, you will be sending some of your data to the
            respective third-party bot developers.
          </span>
          <br />
        </p>
        <p>
          <span style={ContentStyle}>6.2. How Bots Can Receive Data</span>
        </p>
        <p>
          <span style={ContentStyle}>
            You can send data to bot developers when you interact with their
            bots in one of these ways:
          </span>
          <br />
        </p>
        <p>
          <span style={ContentStyle}>By sending messages to a bot.</span>
        </p>
        <p>
          <span style={ContentStyle}>By using an inline bot.</span>
        </p>
        <p>
          <span style={ContentStyle}>
            By participating in a group with a bot.
          </span>
        </p>
        <p>
          <span style={ContentStyle}>
            By pressing buttons in messages sent by a bot.
          </span>
        </p>
        <p>
          <span style={ContentStyle}>
            By paying for goods and services via bots (see section 7 below).
          </span>
        </p>
        <p>
          <span style={ContentStyle}>6.3. What Data Bots Receive</span>
        </p>
        <p>
          <span style={ContentStyle}>
            In any of the above cases, the developers of an automated user (bot)
            can get your public account data (see section 3.1 above): your
            screen name, username and profile picture(s).
          </span>
          <br />
        </p>
        <p>
          <span style={ContentStyle}>
            Bots can also receive the following data when you interact with
            them.
          </span>
          <br />
        </p>
        <p>
          <span style={ContentStyle}>
            Bots will obviously get your messages when you send them something.
          </span>
        </p>
        <p>
          <span style={ContentStyle}>
            If you click on links or buttons provided by the bot, the bot can
            potentially get your IP address (provided that it controls the
            website to which the link leads).
          </span>
        </p>
        <p>
          <span style={ContentStyle}>
            If the bot is a member of the same group with you, it may know you
            are a member.
          </span>
        </p>
        <p>
          <span style={ContentStyle}>
            When you start your message with the username of an inline bot (e.g.
            @gif) the interface transforms so that everything you type becomes a
            query to that bot. This query is sent to the bot so that it can
            provide its service. We will warn you about this the first time you
            use an inline bot.
          </span>
        </p>
        <p>
          <span style={ContentStyle}>
            Bots added to groups can operate in two modes: with access to
            messages in the group or without access. If the bot has access to
            messages, it can see everything that happens in the group. The
            interface clearly shows whether or not a bot has access to messages
            in groups.
          </span>
        </p>
        <p>
          <span style={ContentStyle}>
            6.4. Bots Are Not Maintained by Dinero
          </span>
        </p>
        <p>
          <span style={ContentStyle}>
            Other than our own bots, no other bots or third-party bot developers
            are affiliated with Dinero. They are completely independent from us.
            They should ask you for your permission before they access your data
            or you make it available to them.
          </span>
          <br />
        </p>
        <p>
          <span style={TitleStyle}>7.</span>
          <span style={ContentStyle}> Third Party Payment Services</span>
        </p>
        <p>
          <span style={ContentStyle}>7.1. Payment Information</span>
        </p>
        <p>
          <span style={ContentStyle}>
            The Payment Platform for Bots is available to users as of Dinero
            4.0. Dinero does not process payments from users and instead relies
            on different payment providers around the world. It is the payment
            providers that handle and store your credit card details. Neither
            Dinero nor the merchants on the platform (bot developers) have
            access to this information. Although we work with payment providers
            they are completely independent from Dinero. Please study their
            relevant privacy policies before making your data available to them.
          </span>
          <br />
        </p>
        <p>
          <span style={ContentStyle}>7.2. Credit Card Information</span>
        </p>
        <p>
          <span style={ContentStyle}>
            When making a purchase, you enter your credit card details into a
            form supplied by the payment provider that will be processing the
            payment, and this information goes directly to the payment
            provider's server. Your credit card information never reaches
            Dinero's servers. We do not access and do not store your credit card
            information. When you save your credit card info, it is saved on the
            respective payment provider's servers and the payment provider gives
            Dinero a token that you can reuse for future payments. It is not
            possible to reconstruct your credit card info from the token.
          </span>
          <br />
        </p>
        <p>
          <span style={ContentStyle}>7.3 Shipping Information</span>
        </p>
        <p>
          <span style={ContentStyle}>
            When you enter shipping information in the process of placing an
            order, we send it directly to the merchant bot developer. We can
            store your shipping information for you if you choose to save it for
            future purchases. We will delete this information immediately if you
            ask us to.
          </span>
          <br />
        </p>
        <p>
          <span style={ContentStyle}>7.4. Clearing Payment Information</span>
        </p>
        <p>
          <span style={ContentStyle}>
            You can clear all payment information associated with your account
            at any time by going to Dinero Settings &gt; Privacy &amp; Security
            &gt; Data Settings and selecting ‘Clear Payment &amp; Shipping
            Info’. If you choose to remove your payment information, we will
            delete your stored shipping info and payment tokens from all
            providers and ask the payment providers to remove your credit card
            information that they store.
          </span>
          <br />
        </p>
        <p>
          <span style={ContentStyle}>7.5. Payment Disputes</span>
        </p>
        <p>
          <span style={ContentStyle}>
            Due to the fact that Dinero doesn't store any credit card details or
            transaction information, it is impossible for us to handle
            complaints or cashbacks – any disputed payments are the
            responsibility of the bot developers, payment providers, and banks
            that participated in the exchange.
          </span>
          <br />
        </p>
        <p>
          <span style={TitleStyle}>8.</span>
          <span style={ContentStyle}>
            {" "}
            Who Your Personal Data May Be Shared With
          </span>
        </p>
        <p>
          <span style={ContentStyle}>8.1. Other Dinero Users</span>
        </p>
        <p>
          <span style={ContentStyle}>
            Other users of our Services with whom you choose to communicate with
            and share certain information, who may be located outside the EEA.
            Note that by entering into the Terms of Service and choosing to
            communicate with such other users of Dinero, you are instructing us
            to transfer your personal data, on your behalf, to those users in
            accordance with this Privacy Policy. We employ all appropriate
            technical and organizational measures (including encryption of your
            personal data) to ensure a level of security for your personal data
            that is appropriate to the risk.
          </span>
          <br />
        </p>
        <p>
          <span style={ContentStyle}>8.2. Dinero’s Group Companies</span>
        </p>
        <p>
          <span style={ContentStyle}>
            To provide, improve and support our Services, we may share your
            personal data with: (1) our parent company, Dinero Group Inc,
            located in the British Virgin Islands, (2) Telegraph Inc., a group
            member also located in the BVI; and (3) Dinero FZ-LLC, a group
            member located in Dubai. We will implement appropriate safeguards to
            protect the security and integrity of that personal data. This will
            take the form of standard contract clauses approved by the European
            Commission in an agreement between us and our relevant group
            companies. If you would like more information regarding these
            clauses, please contact our EEA representative using the details in
            section 1.4 above.
          </span>
          <br />
        </p>
        <p>
          <span style={ContentStyle}>8.3. Law Enforcement Authorities</span>
        </p>
        <p>
          <span style={ContentStyle}>
            If Dinero receives a court order that confirms you're a terror
            suspect, we may disclose your IP address and phone number to the
            relevant authorities. So far, this has never happened. When it does,
            we will include it in a semiannual transparency report published at:
            https://t.me/transparency.
          </span>
          <br />
        </p>
        <p>
          <span style={ContentStyle}>
            8.4. Translation of Chats, Channels and specific Messages at the
            Request of the User
          </span>
        </p>
        <p>
          <span style={ContentStyle}>
            Users can choose to translate a specific text message into a
            different language by tapping “Translate” in the action menu of the
            message (to enable this option, a user should first turn on
            Translation services in the Settings &gt; Languages section of the
            Dinero application). Dinero Premium users can also optionally enable
            automatic live translation on any chat, group or channel.
          </span>
          <br />
        </p>
        <p>
          <span style={ContentStyle}>
            Since Dinero may rely on a third-party, Google LLC, subsidiary of
            Alphabet Inc, for automatic translation of messages, the text of any
            message or set of messages that users choose to translate may be
            shared with Google in order to obtain their translated versions.
            Google will only access the data to provide a translation and will
            not use it for any other Google products, services, or advertising.
          </span>
          <br />
        </p>
        <p>
          <span style={ContentStyle}>
            8.5. Transcription of Voice and Video Messages at the Request of the
            User
          </span>
        </p>
        <p>
          <span style={ContentStyle}>
            Some users can choose to convert a voice or video message to text by
            tapping on the Voice-to-Text icon (“-&gt;A”) displayed on eligible
            messages (to be able to use this option, users should subscribe to
            Dinero Premium in the Settings &gt; Dinero Premium section of the
            Dinero application).
          </span>
          <br />
        </p>
        <p>
          <span style={ContentStyle}>
            Since Dinero may rely on a third party, Google LLC, subsidiary of
            Alphabet Inc, for voice-to-text conversion, the audio data of voice
            and video messages that users choose to convert to text may be
            shared with Google in order to obtain their transcribed versions.
            Only audio data may be shared for this purpose (no other data, such
            as the user's IP address or any information about their account is
            shared). According to the agreement between Dinero and Google,
            Dinero will pay for the transcriptions on behalf of its users and
            Google will only access the audio data to provide a transcribed
            version – it will not log audio data or transcripts, and will not
            use the data for any other Google products, services, or
            advertising.
          </span>
          <br />
        </p>
        <p>
          <span style={TitleStyle}>9.</span>
          <span style={ContentStyle}>
            {" "}
            Your Rights Regarding the Personal Data You Provide to Us
          </span>
        </p>
        <p>
          <span style={ContentStyle}>9.1. Your Rights</span>
        </p>
        <p>
          <span style={ContentStyle}>
            Under applicable data protection legislation, in certain
            circumstances, you have rights concerning your personal data. You
            have a right to: (1) request a copy of all your personal data that
            we store and to transmit that copy to another data controller; (2)
            delete (see section 10 below) or amend your personal data; (3)
            restrict, or object to, the processing of your personal data; (4)
            correct any inaccurate or incomplete personal data we hold on you;
            and (5) lodge a complaint with national data protection authorities
            regarding our processing of your personal data.
          </span>
          <br />
        </p>
        <p>
          <span style={ContentStyle}>9.2. Exercising Your Rights</span>
        </p>
        <p>
          <span style={ContentStyle}>
            If you wish to exercise any of these rights, kindly use the contact
            details in section 12 below.
          </span>
          <br />
        </p>
        <p>
          <span style={ContentStyle}>9.3. Data Settings</span>
        </p>
        <p>
          <span style={ContentStyle}>
            You can control how your data is used (e.g., delete synced contacts)
            in Settings &gt; Privacy &amp; Security &gt; Data Settings (using
            one of our mobile apps).
          </span>
          <br />
        </p>
        <p>
          <span style={ContentStyle}>
            Sadly, if you're not OK with Dinero's modest minimum requirements,
            it won't be possible for us to provide you with our Services. You
            can delete your Dinero account by proceeding to the deactivation
            page.
          </span>
          <br />
        </p>
        <p>
          <span style={TitleStyle}>10.</span>
          <span style={ContentStyle}> Deleting data</span>
        </p>
        <p>
          <span style={ContentStyle}>10.1. Accounts</span>
        </p>
        <p>
          <span style={ContentStyle}>
            If you would like to delete your account, you can do this on the
            deactivation page. Deleting your account removes all messages,
            media, contacts and every other piece of data you store in the
            Dinero cloud. This action must be confirmed via your Dinero account
            and cannot be undone.
          </span>
          <br />
        </p>
        <p>
          <span style={ContentStyle}>10.2. Messages</span>
        </p>
        <p>
          <span style={ContentStyle}>
            In secret chats, deleting a message always instructs the app on the
            other end to delete it too.
          </span>
        </p>
        <p>
          <span style={ContentStyle}>
            In cloud chats, you can choose to delete a message for all
            participants within at least 48 hours after sending. Otherwise,
            deleting a message will delete it from your message history. This
            means that a copy will stay on the server as part of your partner's
            message history. As soon as your partner deletes it too, it's gone
            forever.
          </span>
        </p>
        <p>
          <span style={ContentStyle}>
            As of version 5.5, any party can choose to delete any messages in
            one-on-one chats, both sent and received, for both sides. There is
            no time limit. Any party can also opt to clear the entire chat
            history for both parties, in which case the apps will be instructed
            to remove all messages in that chat, regardless of how many messages
            are retained by either of the participants.
          </span>
        </p>
        <p>
          <span style={ContentStyle}>
            In supergroups and channels, deleting a message removes it for all
            participants. Note that deleted messages and original versions of
            edited messages from supergroups are stored for 48 hours after
            deletion in order to be shown in the admins log.
          </span>
        </p>
        <p>
          <span style={ContentStyle}>10.3. Self-Destructing Messages</span>
        </p>
        <p>
          <span style={ContentStyle}>
            Messages in Secret Chats can be ordered to self-destruct. As soon as
            such a message is read (2 checks appear), the countdown starts. When
            the timer expires, both devices participating in a secret chat are
            instructed to delete the message (photo, video, etc.). Media with
            short timers (less than a minute) are shown with blurred previews.
            The timer is triggered when they are viewed.
          </span>
          <br />
        </p>
        <p>
          <span style={ContentStyle}>10.4. Account Self-Destruction</span>
        </p>
        <p>
          <span style={ContentStyle}>
            By default, if you stop using Dinero and do not come online for at
            least 6 months, your account will be deleted along with all
            messages, media, contacts and every other piece of data you store in
            the Dinero cloud. You can go to Settings to change the exact period
            after which your inactive account will self-destruct.
          </span>
          <br />
        </p>
        <p>
          <span style={TitleStyle}>11.</span>
          <span style={ContentStyle}> Changes to this Privacy Policy</span>
        </p>
        <p>
          <span style={ContentStyle}>
            We will review and may update this Privacy Policy from time to time.
            Any changes to this Privacy Policy will become effective when we
            post the revised Privacy Policy on this page www.Dinero.org/privacy.
            Please check our website frequently to see any updates or changes to
            our Privacy Policy, a summary of which we will set out below.
          </span>
          <br />
        </p>
        <p>
          <span style={ContentStyle}>March 25, 2019</span>
          <br />
        </p>
        <p>
          <span style={ContentStyle}>
            Expanded 10.2. Deleting Messages with data on the new features in
            version 5.5, which allow both participants to remove any messages
            from one-on-one chats for both sides without a time limit.
          </span>
        </p>
        <p>
          <span style={ContentStyle}>March 24, 2021</span>
          <br />
        </p>
        <p>
          <span style={ContentStyle}>Added 3.5. Location Data.</span>
        </p>
        <p>
          <span style={ContentStyle}>
            Improved structure, moving 3.3.5 to 3.4 and 3.3.6 to 3.6.
          </span>
        </p>
        <p>
          <span style={ContentStyle}>October 26, 2021</span>
          <br />
        </p>
        <p>
          <span style={ContentStyle}>
            Expanded 5.6. No Ads Based on User Data with information about
            sponsored messages in public channels.
          </span>
        </p>
        <p>
          <span style={ContentStyle}>June 19, 2022</span>
          <br />
        </p>
        <p>
          <span style={ContentStyle}>
            Added 8.4. Translation of Messages at the Request of the User and
            8.5. Transcription of Voice Messages at the Request of the User.
          </span>
        </p>
        <p>
          <span style={ContentStyle}>September 8, 2022</span>
          <br />
        </p>
        <p>
          <span style={ContentStyle}>
            Expanded 3.2. Your Email Address with information on login emails,
            available as of Dinero 9.0
          </span>
        </p>
        <p>
          <span style={ContentStyle}>February 3, 2022</span>
          <br />
        </p>
        <p>
          <span style={ContentStyle}>
            Updated 8.4 and 8.5 to reflect the new premium feature that allows
            translating entire chats.
          </span>
        </p>
        <p>
          <span style={ContentStyle}>April 24, 2023</span>
          <br />
        </p>
        <p>
          <span style={ContentStyle}>
            Updated 1.4, 9.2 and 12 to update the details of Dinero’s EEA
            representative for GDPR matters.
          </span>
        </p>
        <p>
          <span style={ContentStyle}>
            Updated 8.2 to mention Telegraph Inc., a member of the Dinero group
            of companies.
          </span>
        </p>
        <p>
          <span style={ContentStyle}>
            Important changes made to this Privacy Policy will be notified to
            you via Dinero.
          </span>
        </p>
      </div>
    </div>
  );
};
export default Policy;
